version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - cescoffier
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-sns
    versions:
    - ">= 0"
  - dependency-name: com.google.cloud:libraries-bom
    versions:
    - ">= 0"
  - dependency-name: io.smallrye.reactive:*
    versions:
    - ">= 0"
  - dependency-name: io.smallrye:smallrye-config
    versions:
    - "<2.0.0"
  - dependency-name: io.smallrye:smallrye-fault-tolerance
    versions:
    - "<5.0.0"
  - dependency-name: io.smallrye:smallrye-health
    versions:
    - "<3.0.0"
  - dependency-name: io.vertx:vertx-stack-depchain
    versions:
    - "<4.0.0"
  - dependency-name: org.eclipse.microprofile.metrics:microprofile-config-api
    versions:
    - "<2.0.0"
  - dependency-name: org.eclipse.microprofile.metrics:microprofile-health-api
    versions:
    - "<3.0"
  - dependency-name: org.eclipse.microprofile.metrics:microprofile-metrics-api
    versions:
    - "<3.0.0"
  - dependency-name: org.eclipse:yasson
    versions:
    - ">= 0"
  - dependency-name: software.amazon.awssdk:*
    versions:
    - ">= 0"
  - dependency-name: io.smallrye.config:smallrye-config
    versions:
    - 2.1.0
    - 2.2.0
  - dependency-name: org.jboss.weld:weld-junit5
    versions:
    - 3.0.0.Final
  - dependency-name: io.cloudevents:cloudevents-api
    versions:
    - 2.0.0
  - dependency-name: org.eclipse.microprofile.config:microprofile-config-api
    versions:
    - "2.0"
  - dependency-name: org.eclipse.microprofile.health:microprofile-health-api
    versions:
    - "3.0"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: 2.x
  reviewers:
  - cescoffier
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-sns
    versions:
    - ">= 0"
  - dependency-name: com.google.cloud:libraries-bom
    versions:
    - ">= 0"
  - dependency-name: io.smallrye.reactive:*
    versions:
    - ">= 0"
  - dependency-name: io.smallrye:smallrye-config
    versions:
    - ">=2.0.0"
  - dependency-name: io.smallrye:smallrye-fault-tolerance
    versions:
    - ">=5.0.0"
  - dependency-name: io.smallrye:smallrye-health
    versions:
    - ">=3.0.0"
  - dependency-name: io.smallrye:smallrye-metrics
    versions:
    - ">=3.0.0"
  - dependency-name: io.vertx:vertx-stack-depchain
    versions:
    - ">=4.0.0"
  - dependency-name: org.eclipse.microprofile.metrics:microprofile-config-api
    versions:
    - ">=2.0.0"
  - dependency-name: org.eclipse.microprofile.metrics:microprofile-metrics-api
    versions:
    - ">=3.0.0"
  - dependency-name: org.eclipse.microprofile.metrics:mmicroprofile-health-api
    versions:
    - ">=3.0"
  - dependency-name: org.eclipse:yasson
    versions:
    - ">= 0"
  - dependency-name: software.amazon.awssdk:*
    versions:
    - ">= 0"
  - dependency-name: org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-core
    versions:
    - "2.0"
  - dependency-name: org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-api
    versions:
    - "2.0"
  - dependency-name: org.eclipse.microprofile.health:microprofile-health-api
    versions:
    - "3.0"
  - dependency-name: io.smallrye.config:smallrye-config
    versions:
    - 2.2.0
  - dependency-name: org.eclipse.microprofile.config:microprofile-config-api
    versions:
    - "2.0"
  - dependency-name: io.cloudevents:cloudevents-api
    versions:
    - 2.0.0
  - dependency-name: org.jboss.weld:weld-junit5
    versions:
    - 3.0.0.Final
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.3
