---
name: Pull Request Build

on:
    pull_request:
        branches:
            - main
            - 2.x

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [
                    {'version': '8'},
                    {'version': '11'},
                    {
                        'version': '16',
                        'opts': '--illegal-access=permit' # required for kotlin
                    },
                    {
                        'version': '17-ea',
                        'opts': '--illegal-access=permit' # required for kotlin
                    }
                ]
        name: Build with Java ${{ matrix.java.version }}
        steps:
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      maven-
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java.version }}
                  distribution: adopt
            - name: Build with Maven
              env:
                  MAVEN_OPTS: ${{ matrix.java.opts }}
              run: |
                 mvn -s .github/ci-maven-settings.xml \
                    -B clean verify -Dtest-containers=true


    up_to_date_antora:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: adopt
            - name: Build with Maven
              run: | # Fail the build is the antora.yaml becomes out of date
                  mvn -s .github/ci-maven-settings.xml -B install -DskipTests
                  mvn -s .github/ci-maven-settings.xml -B \
                    -pl documentation scm:check-local-modification \
                    -Dincludes=src/main/doc/antora.yml
